# Generated by Django 4.0.4 on 2022-05-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(default=' ', max_length=2000)),
                ('sensor_model', models.CharField(default=' ', max_length=2000)),
                ('value', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(default=' ', max_length=2000)),
                ('device_model', models.CharField(default=' ', max_length=2000)),
                ('sensors', models.ManyToManyField(to='device.sensor')),
            ],
        ),
    ]
