# Generated by Django 4.0.4 on 2022-05-06 10:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.CharField(default='mission_default', max_length=2000)),
                ('mission_id', models.CharField(default='M', max_length=2000)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField()),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='device.device')),
                ('locations', models.ManyToManyField(null=True, to='route.location')),
            ],
        ),
    ]
