# Generated by Django 4.0.4 on 2022-05-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='mission_id',
            field=models.CharField(default='M', max_length=2000),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_name',
            field=models.CharField(default='M', max_length=2000),
        ),
    ]
