# Generated by Django 4.0.4 on 2022-05-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.FloatField(default=0.0)),
                ('lat', models.FloatField(default=0.0)),
                ('locname', models.CharField(default=' ', max_length=2000)),
            ],
        ),
    ]
